[package]
name = "wry"
version = "0.5.1"
authors = ["Ngo Iok Ui <wusyong9104@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "Cross-platform WebView rendering library"
readme = "README.md"
repository = "https://github.com/tauri-apps/wry"
documentation = "https://docs.rs/wry"
categories = ["gui"]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu", "x86_64-apple-darwin"]

[dependencies]
libc = "0.2"
once_cell = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
url = "2.2"
image = "0.23"

[target.'cfg(target_os = "linux")'.dependencies]
cairo-rs = "0.9"
webkit2gtk = { version = "0.11", features = ["v2_8"] }
gio = "0.9"
gtk = "0.9"
gdk = "0.13"
gdk-pixbuf = "0.9"
glib = "0.10"

[target.'cfg(target_os = "windows")'.dependencies]
webview2 = "0.1.0-beta.1"
winapi = { version = "0.3", features = ["libloaderapi"] }
winit = "0.24"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
core-graphics = "0.22"
objc = "0.2"
winit = "0.24"
