workspace = { }

[package]
name = "wry"
version = "0.8.0"
authors = [ "Tauri Programme within The Commons Conservancy" ]
edition = "2018"
license = "Apache-2.0 OR MIT"
description = "Cross-platform WebView rendering library"
readme = "README.md"
repository = "https://github.com/tauri-apps/wry"
documentation = "https://docs.rs/wry"
categories = [ "gui" ]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = [
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin"
]

[features]
default = [ "file-drop", "protocol", "win32" ]
file-drop = [ ]
protocol = [ ]
winrt = [ "windows-webview2", "windows" ]
win32 = [ "webview2", "winapi" ]

[dependencies]
libc = "0.2"
log = "0.4"
once_cell = "1.7"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
thiserror = "1.0"
url = "2.2"
image = "0.23"
infer = "0.4"

[target."cfg(target_os = \"linux\")".dependencies]
cairo-rs = "0.9"
webkit2gtk = { version = "0.11", features = [ "v2_8" ] }
gio = "0.9"
glib = "0.10"
gtk = "0.9"
gdk = "0.13"
gdk-pixbuf = "0.9"
async-channel = "1.6"

[target."cfg(target_os = \"windows\")".dependencies]
webview2 = { version = "0.1.0-beta.1", optional = true }
winapi = { version = "0.3", features = [ "libloaderapi", "oleidl" ], optional = true }
windows-webview2 = { version = "0.1", optional = true }
windows = { version = "0.7", optional = true }
tauri-winit = "0.24"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.24"
core-graphics = "0.22"
objc = "0.2"
objc_id = "0.1"
tauri-winit = "0.24"
