workspace = { }

[package]
name = "wry"
version = "0.12.2"
authors = [ "Tauri Programme within The Commons Conservancy" ]
edition = "2018"
license = "Apache-2.0 OR MIT"
description = "Cross-platform WebView rendering library"
readme = "README.md"
repository = "https://github.com/tauri-apps/wry"
documentation = "https://docs.rs/wry"
categories = [ "gui" ]

[package.metadata.docs.rs]
features = [ "dox" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin"
]

[features]
default = [ "file-drop", "protocol", "tray" ]
file-drop = [ ]
protocol = [ ]
dox = [ "tao/dox" ]
tray = [ "tao/tray" ]

[dependencies]
libc = "0.2"
log = "0.4"
once_cell = "1.8"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
thiserror = "1.0"
url = "2.2"
tao = { version = "0.5.2", default-features = false, features = [ "serde" ] }
http = "0.2.5"

[dev-dependencies]
anyhow = "1.0.43"
chrono = "0.4.19"
tempfile = "3.2.0"
http-range = "0.1.4"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
webkit2gtk = { version = "0.14", features = [ "v2_18" ] }
webkit2gtk-sys = "0.15"
gio = "0.14"
glib = "0.14"
gtk = "0.14"
gdk = "0.14"

[target."cfg(target_os = \"windows\")".dependencies]
webview2 = "0.1"
webview2-sys = "0.1"
winapi = { version = "0.3", features = [ "libloaderapi", "oleidl" ] }

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
cocoa = "0.24"
core-graphics = "0.22"
objc = "0.2"
objc_id = "0.1"
